### ISSUE TITLE
doesnt compile on os x

### ISSUE THREAD

**Issue by w-A-L-L-e** [anrieff/sdl-minimal#1]
➜  sdl-minimal git:(master) g++ main.cpp -lsdl
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: _SDL_main)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

same error for c++ and make commands...

**Comment by w-A-L-L-e** [comment]
Thanks for a minimal exaample however on os x Mojave we need another flag or some other changes to the source code. Would be nice to put them in the README...

**Comment by anrieff** [comment]
Which SDL version are you using?
You may need to link in SDLmain, e.g.

`g++ main.cpp -o sdl-minimal -lSDL -lSDLmain -lpthread`

If this fixes it, I'll be glad to update the Readme.

**Comment by sy2002** [comment]
@anrieff and @w-A-L-L-e : On my Mac, I can compile it using this command line:

clang main.cpp \`sdl-config --cflags --libs\`

and also 

g++ main.cpp \`sdl-config --cflags --libs\`

Using the backticks \`  \` and embedding the sdl-config --cflags --libs command in backticks on the macOS commandline leads to giving the right parameters to the compiler for the local installation.

Try running `sdl-config --cflags and --libs` directly on the macOS terminal and you will see, what parameters it passes to the compiler (g++ and/or clang).

I am using SDL 1.2.15.

But I am running into a different problem: It compiles fine and I also can run it. But what happens: It starts, waits 5 seconds and outputs "Exited cleanly". No window is openend, no gradient is shown.

**Comment by anrieff** [comment]
@sy2002, this is a Mac-specific thing, that a GUI app needs to be in an app bundle. See [here](https://github.com/SDL-mirror/SDL/blob/master/docs/README-macosx.md), more specifically the section titled "Using the Simple DirectMedia Layer with a traditional Makefile".

**Comment by sy2002** [comment]
@anrieff: Thank you, very valuable input!

FYI, might be interessting for you, too: While in the meantime switching to SDL2 for my project, I found out, that also on macOS - at least with SDL2 - no app bundle at all is necessary any more. You can just compile on the command line and run. Here is a sample GIST:

https://gist.github.com/sy2002/c7bfa44a7d9d30e3863797af72b98646

And here is how to compile on the command line (runs like a charm):
clang sdltest.c -o sdltest \`sdl2-config --cflags --libs\`

**Comment by anrieff** [comment]
I vaguely remember this possibility was added in either Leopard or Snow Leopard, that after issuing a specific MacOS call, the app becomes a fully-fledged "foreground" task even if it didn't have an app bundle. My recollection back then was that the preferred way was still to have an app bundle, the call was more of a hack that's frowned upon. It may be that this is no longer the case. I guess that SDL2 is doing this call under the hood, and SDL1.2 isn't.
Anyway, I'm closing the issue as the \`sdl-config --cflags --libs\` approach you mention resolves the original issue with building the example.
